sudo: required
services:
  - docker

before_install:
  - docker build -t alessandro86495/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true alessandro86495/react-test npm test

after_success:
  - docker build -t alessandro86495/multi-client ./client
  - docker build -t alessandro86495/multi-nginx ./nginx
  - docker build -t alessandro86495/multi-server ./server
  - docker build -t alessandro86495/multi-worker ./worker
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push alessandro86495/multi-client
  - docker push alessandro86495/multi-nginx
  - docker push alessandro86495/multi-server
  - docker push alessandro86495/multi-worker